# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dyne' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dyne
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'QRCodeReader.swift'
end
